"""Text-format writers (srt, csv, docx) for InstaScribe exports."""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any


def _timecode_srt(secs: float) -> str:
    """Format seconds as SRT timecode: HH:MM:SS,mmm."""
    if secs < 0:
        secs = 0.0
    h = int(secs // 3600)
    m = int((secs % 3600) // 60)
    s = int(secs % 60)
    ms = int(round((secs - int(secs)) * 1000))
    if ms >= 1000:
        s += 1
        ms = 0
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def _timecode_hms(secs: float) -> str:
    """Format seconds as H:MM:SS for human reading."""
    h = int(secs // 3600)
    m = int((secs % 3600) // 60)
    s = int(secs % 60)
    if h:
        return f"{h}:{m:02d}:{s:02d}"
    return f"{m}:{s:02d}"


def write_srt(scenes: list[dict[str, Any]], out_path: Path) -> Path:
    """Write SRT for active scenes. `scenes` already merged with overrides."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    cue = 1
    for s in scenes:
        if not s.get("active", True):
            continue
        text = (s.get("text") or "").strip()
        if not text:
            continue
        start = float(s.get("start", 0.0))
        end = float(s.get("end", start))
        lines.append(str(cue))
        lines.append(f"{_timecode_srt(start)} --> {_timecode_srt(end)}")
        lines.append(text)
        lines.append("")
        cue += 1
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


def write_csv(scenes: list[dict[str, Any]], out_path: Path) -> Path:
    """Write CSV of every scene (active flag included for triage)."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cols = ["scene_id", "start", "end", "duration", "active", "voice", "characters", "ad_text"]
    with out_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for s in scenes:
            start = float(s.get("start", 0.0))
            end = float(s.get("end", start))
            w.writerow(
                {
                    "scene_id": s.get("scene_id", ""),
                    "start": f"{start:.3f}",
                    "end": f"{end:.3f}",
                    "duration": f"{max(0.0, end - start):.3f}",
                    "active": "1" if s.get("active", True) else "0",
                    "voice": s.get("voice", ""),
                    "characters": ";".join(s.get("character_ids", []) or []),
                    "ad_text": (s.get("text") or "").replace("\r", " ").replace("\n", " ").strip(),
                }
            )
    return out_path


def write_docx(
    project_name: str,
    scenes: list[dict[str, Any]],
    entities_by_id: dict[str, dict[str, Any]],
    out_path: Path,
) -> Path:
    """Write a formatted AD script document."""
    from docx import Document
    from docx.shared import Pt

    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc = Document()
    doc.add_heading(project_name or "Audio Description Script", level=0)
    doc.add_paragraph("Generated by InstaScribe. Active scenes only — inactive scenes are omitted.")

    for s in scenes:
        if not s.get("active", True):
            continue
        text = (s.get("text") or "").strip()
        if not text:
            continue
        start = float(s.get("start", 0.0))
        end = float(s.get("end", start))
        scene_id = s.get("scene_id", "")
        heading = f"{scene_id}  ·  {_timecode_hms(start)} – {_timecode_hms(end)}"
        h = doc.add_heading(heading, level=2)
        for run in h.runs:
            run.font.size = Pt(12)

        char_ids = s.get("character_ids") or []
        if char_ids:
            names = [entities_by_id.get(cid, {}).get("name", cid) for cid in char_ids]
            p = doc.add_paragraph()
            p.add_run("Characters: ").bold = True
            p.add_run(", ".join(names))

        body = doc.add_paragraph(text)
        for run in body.runs:
            run.font.size = Pt(11)

    doc.save(str(out_path))
    return out_path
